include:
  - local: '.gitlab-ci/cicd-templates/docker-build-template.yml'
  - local: '.gitlab-ci/cicd-templates/dotnet-package-template.yml'
  - local: '.gitlab-ci/cicd-templates/deploy-template.yml'
stages:
  # - package
  - build
  - deploy
variables:
  SERVICE_NAME: bps-admin-ui
  SERVICE_ROOT_DIR: src
  SERVICE_DIR: src/Bps.Admin.UI
  SERVICE_DOCKERFILE: DockerfileUi
  NAMESPACE: bps

# bps-admin-ui-package:
#   stage: package
#   extends: .dotnet-package

bps-admin-ui-build:
  stage: build
  # needs: ["bps-admin-ui-package"]
  extends: .build-push

bps-admin-ui-deploy:
  stage: deploy
  needs: ["bps-admin-ui-build"]
  extends: .deploy

