include:
  - local: '.gitlab-ci/templates/docker-build-template.yml'
  - local: '.gitlab-ci/templates/dotnet-package-template.yml'
  - local: '.gitlab-ci/templates/deploy-template.yml'
stages:
  # - package
  - build
  - deploy
variables:
  SERVICE_NAME: xyz-admin-ui
  SERVICE_ROOT_DIR: src
  SERVICE_DIR: src/Xyz.Admin.UI
  SERVICE_DOCKERFILE: DockerfileUi
  NAMESPACE: xyz


xyz-admin-ui-build:
  stage: build
  # needs: ["xyz-admin-ui-package"]
  extends: .build-push

xyz-admin-ui-deploy:
  stage: deploy
  needs: ["xyz-admin-ui-build"]
  extends: .deploy

