include:
  - local: '.gitlab-ci/templates/docker-build-template.yml'
  - local: '.gitlab-ci/templates/deploy-template.yml'
stages:
  # - package
  - build
  - deploy
variables:
  SERVICE_NAME: xyz-admin-api
  SERVICE_ROOT_DIR: src
  SERVICE_DIR: src/Xyz.Admin.Api
  SERVICE_DOCKERFILE: DockerfileApi
  NAMESPACE: xyz


xyz-admin-api-build:
  stage: build
  # needs: ["bps-admin-api-package"]
  extends: .build-push

bps-admin-api-deploy:
  stage: deploy
  needs: ["xyz-admin-api-build"]
  extends: .deploy

